"""
sdd agent — manage custom sub-agents for Claude Code (and equivalents for other agents).

Subcommands:
  sdd agent list                        # list all agents (built-in + custom)
  sdd agent new <name>                  # scaffold a new custom agent
  sdd agent edit <name>                 # open an agent file for editing
  sdd agent show <name>                 # print agent content
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table

agent_app = typer.Typer(no_args_is_help=True)
console = Console()

CUSTOM_AGENT_TEMPLATE = """\
# Agent: {name}
# Custom agent — generated by spec-builder
#
# Claude Code: invoke with /agent {name}
# Other agents: paste this content into your agent chat as context.

## Role

<!-- Describe the agent's role in one sentence. -->

## Trigger

Use this agent when:
- <!-- condition 1 -->
- <!-- condition 2 -->

## Mandatory Reading Order

Before acting, read:

1. `.specify/memory/constitution.md`
2. `.specify/specs/<active-spec>/spec.md`
3. `.specify/specs/<active-spec>/plan.md`
4. `.specify/specs/<active-spec>/tasks.md`

## Instructions

<!-- Step-by-step instructions for what this agent should do. -->

1. 
2. 
3. 

## Constraints

- Do not implement anything outside the active spec.
- Do not contradict the constitution.
- Stop and ask if there is ambiguity.

## Output Format

<!-- Describe what the agent should produce. -->

```
Summary: <one line>
Actions taken: <list>
Files modified: <list>
Follow-up needed: <yes/no + reason>
```
"""


def _find_project_root(start: Path) -> Path:
    current = start
    for _ in range(10):
        if (current / ".specify").exists():
            return current
        current = current.parent
    return start


def _agents_dir(project_root: Path) -> Path:
    return project_root / ".claude" / "agents"


def _builtin_agents(project_root: Path) -> dict[str, Path]:
    agents: dict[str, Path] = {}
    d = _agents_dir(project_root)
    if d.exists():
        for p in sorted(d.glob("*.md")):
            if not p.name.startswith("custom-"):
                agents[p.stem] = p
    return agents


def _custom_agents(project_root: Path) -> dict[str, Path]:
    agents: dict[str, Path] = {}
    d = _agents_dir(project_root) / "custom"
    if d.exists():
        for p in sorted(d.glob("*.md")):
            agents[f"custom/{p.stem}"] = p
    return agents


def _all_agents(project_root: Path) -> dict[str, Path]:
    return {**_builtin_agents(project_root), **_custom_agents(project_root)}


def _open_editor(path: Path) -> None:
    editor = os.environ.get("EDITOR") or os.environ.get("VISUAL")
    if editor:
        subprocess.run([editor, str(path)])
    elif sys.platform == "darwin":
        subprocess.run(["open", "-t", str(path)])
    elif sys.platform == "win32":
        subprocess.run(["notepad", str(path)])
    else:
        console.print(f"[yellow]Set $EDITOR to open files automatically.[/]")
        console.print(f"File: [cyan]{path}[/]")


@agent_app.command("list")
def agent_list() -> None:
    """List all sub-agents (built-in and custom)."""
    project_root = _find_project_root(Path.cwd())
    agents = _all_agents(project_root)

    if not agents:
        console.print("[yellow]No agents found.[/] Run [bold]sdd init --agent claude-code --profile full[/] to scaffold built-in agents.")
        raise typer.Exit()

    table = Table(title="Sub-agents", show_lines=True)
    table.add_column("Name", style="cyan")
    table.add_column("Type")
    table.add_column("Path")

    for key, path in agents.items():
        kind = "[green]custom[/]" if key.startswith("custom/") else "[dim]built-in[/]"
        table.add_row(key, kind, str(path.relative_to(project_root)))

    console.print(table)
    console.print("\n[dim]Invoke with: /agent <name> (Claude Code)[/]\n")


@agent_app.command("new")
def agent_new(
    name: str = typer.Argument(..., help="Agent name (slug, e.g. 'tester' or 'documenter')"),
    description: str = typer.Option("", "--description", "-d", help="Short description of what this agent does"),
) -> None:
    """Scaffold a new custom sub-agent in .claude/agents/custom/."""
    project_root = _find_project_root(Path.cwd())
    custom_dir = _agents_dir(project_root) / "custom"
    custom_dir.mkdir(parents=True, exist_ok=True)

    dest = custom_dir / f"{name}.md"
    if dest.exists():
        console.print(f"[red]Agent already exists:[/] {dest}")
        raise typer.Exit(1)

    content = CUSTOM_AGENT_TEMPLATE.format(name=name)
    if description:
        content = content.replace("<!-- Describe the agent's role in one sentence. -->", description)

    dest.write_text(content, encoding="utf-8", newline="\n")
    console.print(f"\n[bold green]Created[/] custom agent at [cyan]{dest}[/]")
    console.print(f"Invoke with: [bold]/agent custom/{name}[/] (Claude Code)\n")

    _open_editor(dest)


@agent_app.command("edit")
def agent_edit(
    name: str = typer.Argument(..., help="Agent name (e.g. 'reviewer' or 'custom/tester')"),
) -> None:
    """Open an agent file in your editor."""
    project_root = _find_project_root(Path.cwd())
    agents = _all_agents(project_root)

    if name not in agents:
        console.print(f"[red]Agent '{name}' not found.[/] Run [bold]sdd agent list[/] to see available agents.")
        raise typer.Exit(1)

    _open_editor(agents[name])


@agent_app.command("show")
def agent_show(
    name: str = typer.Argument(..., help="Agent name"),
) -> None:
    """Print the content of an agent file."""
    project_root = _find_project_root(Path.cwd())
    agents = _all_agents(project_root)

    if name not in agents:
        console.print(f"[red]Agent '{name}' not found.[/]")
        raise typer.Exit(1)

    content = agents[name].read_text(encoding="utf-8")
    console.rule(f"[bold cyan]{name}[/]")
    console.print(content)
    console.rule()
