"""
sdd hook — manage Claude Code hooks.

Subcommands:
  sdd hook list                         # list all hooks
  sdd hook edit <name>                  # open a hook file for editing
  sdd hook show <name>                  # print hook content
  sdd hook new <name>                   # scaffold a new custom hook
"""

from __future__ import annotations

import os
import stat
import subprocess
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

hook_app = typer.Typer(no_args_is_help=True)
console = Console()

KNOWN_HOOKS = {
    "pre-edit":      "Runs before Claude edits any file. Exit 1 to block.",
    "post-edit":     "Runs after Claude edits any file. Use for linting/formatting.",
    "post-tool-use": "Runs after any tool call (bash, read, write, etc.).",
    "stop":          "Runs when Claude finishes a session. Use for summaries.",
}

CUSTOM_HOOK_SH_TEMPLATE = """\
#!/usr/bin/env bash
# {name}.sh — custom hook
# Generated by spec-builder
#
# Receives event JSON via stdin.
# Exit 0 = continue, Exit 1 = block with message to stderr.

set -euo pipefail

INPUT=$(cat)

# ── Add your logic below ─────────────────────────────────────────────────────

# Example: extract file path from event
# FILE=$(echo "$INPUT" | grep -o '"path":"[^"]*"' | head -1 | cut -d'"' -f4)

# ─────────────────────────────────────────────────────────────────────────────

exit 0
"""

CUSTOM_HOOK_PS1_TEMPLATE = """\
# {name}.ps1 — custom hook
# Generated by spec-builder
#
# Receives event JSON via stdin.
# Exit 0 = continue, Exit 1 = block.

param([string]$InputJson = "")
if (-not $InputJson) {{ $InputJson = $input | Out-String }}

# ── Add your logic below ─────────────────────────────────────────────────────

# Example: extract file path
# $File = [regex]::Match($InputJson, '"path":"([^"]*)"').Groups[1].Value

# ─────────────────────────────────────────────────────────────────────────────

exit 0
"""


def _find_project_root(start: Path) -> Path:
    current = start
    for _ in range(10):
        if (current / ".specify").exists():
            return current
        current = current.parent
    return start


def _hooks_dir(project_root: Path) -> Path:
    return project_root / ".claude" / "hooks"


def _collect_hooks(project_root: Path) -> dict[str, Path]:
    hooks: dict[str, Path] = {}
    d = _hooks_dir(project_root)
    if not d.exists():
        return hooks
    for p in sorted(d.glob("*.sh")):
        hooks[p.stem] = p
    return hooks


def _open_editor(path: Path) -> None:
    editor = os.environ.get("EDITOR") or os.environ.get("VISUAL")
    if editor:
        subprocess.run([editor, str(path)])
    elif sys.platform == "darwin":
        subprocess.run(["open", "-t", str(path)])
    elif sys.platform == "win32":
        subprocess.run(["notepad", str(path)])
    else:
        console.print(f"[yellow]Set $EDITOR to open files automatically.[/]")
        console.print(f"File: [cyan]{path}[/]")


@hook_app.command("list")
def hook_list() -> None:
    """List all hooks in .claude/hooks/."""
    project_root = _find_project_root(Path.cwd())
    hooks = _collect_hooks(project_root)

    if not hooks:
        console.print("[yellow]No hooks found.[/] Run [bold]sdd init --agent claude-code --profile standard[/] to scaffold built-in hooks.")
        raise typer.Exit()

    table = Table(title="Hooks (.claude/hooks/)", show_lines=True)
    table.add_column("Name", style="cyan")
    table.add_column("Description")
    table.add_column("Files")

    for name, sh_path in hooks.items():
        desc = KNOWN_HOOKS.get(name, "Custom hook")
        ps1 = sh_path.parent / f"{name}.ps1"
        files = f"{sh_path.name}"
        if ps1.exists():
            files += f" + {ps1.name}"
        table.add_row(name, desc, files)

    console.print(table)
    console.print("\n[dim]Hooks are configured in .claude/settings.json[/]\n")


@hook_app.command("new")
def hook_new(
    name: str = typer.Argument(..., help="Hook name (e.g. 'post-tool-use' or 'pre-edit')"),
    description: str = typer.Option("", "--description", "-d", help="Short description"),
) -> None:
    """Scaffold a new hook (.sh + .ps1) in .claude/hooks/."""
    project_root = _find_project_root(Path.cwd())
    hooks_dir = _hooks_dir(project_root)
    hooks_dir.mkdir(parents=True, exist_ok=True)

    sh_dest = hooks_dir / f"{name}.sh"
    ps1_dest = hooks_dir / f"{name}.ps1"

    if sh_dest.exists():
        console.print(f"[red]Hook already exists:[/] {sh_dest}")
        raise typer.Exit(1)

    sh_content = CUSTOM_HOOK_SH_TEMPLATE.format(name=name)
    ps1_content = CUSTOM_HOOK_PS1_TEMPLATE.format(name=name)

    sh_dest.write_text(sh_content, encoding="utf-8", newline="\n")
    sh_dest.chmod(sh_dest.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    ps1_dest.write_text(ps1_content, encoding="utf-8", newline="\n")

    console.print(f"\n[bold green]Created[/] hook at [cyan]{sh_dest}[/] and [cyan]{ps1_dest}[/]")

    if name not in KNOWN_HOOKS:
        console.print(f"\n[yellow]Note:[/] '{name}' is not a standard hook event.")
        console.print(f"Standard hooks: {', '.join(KNOWN_HOOKS.keys())}")
        console.print("Make sure to register it in [bold].claude/settings.json[/] under `hooks`.\n")
    else:
        console.print(f"[dim]{KNOWN_HOOKS[name]}[/]\n")

    _open_editor(sh_dest)


@hook_app.command("edit")
def hook_edit(
    name: str = typer.Argument(..., help="Hook name (e.g. 'pre-edit')"),
    platform: str = typer.Option("sh", "--platform", "-p", help="Platform: sh (default) or ps1"),
) -> None:
    """Open a hook file in your editor."""
    project_root = _find_project_root(Path.cwd())
    hooks_dir = _hooks_dir(project_root)
    ext = "ps1" if platform == "ps1" else "sh"
    target = hooks_dir / f"{name}.{ext}"

    if not target.exists():
        console.print(f"[red]Hook not found:[/] {target}")
        console.print("Run [bold]sdd hook list[/] to see available hooks.")
        raise typer.Exit(1)

    _open_editor(target)


@hook_app.command("show")
def hook_show(
    name: str = typer.Argument(..., help="Hook name"),
    platform: str = typer.Option("sh", "--platform", "-p", help="Platform: sh (default) or ps1"),
) -> None:
    """Print the content of a hook file."""
    project_root = _find_project_root(Path.cwd())
    hooks_dir = _hooks_dir(project_root)
    ext = "ps1" if platform == "ps1" else "sh"
    target = hooks_dir / f"{name}.{ext}"

    if not target.exists():
        console.print(f"[red]Hook not found:[/] {target}")
        raise typer.Exit(1)

    console.rule(f"[bold cyan]{name}.{ext}[/]")
    console.print(target.read_text(encoding="utf-8"))
    console.rule()
