"""
sdd skill — manage Claude Code skills (and equivalents for other agents).

Subcommands:
  sdd skill list                        # list all skills (built-in + custom)
  sdd skill new <name>                  # scaffold a new custom skill
  sdd skill edit <name>                 # open a skill file for editing
  sdd skill show <name>                 # print skill content
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

skill_app = typer.Typer(no_args_is_help=True)
console = Console()

CUSTOM_SKILL_TEMPLATE = """\
# Skill: {name}
# Custom skill — generated by spec-builder
#
# Claude Code: invoke with /skill {name}
# Other agents: paste this content into your agent chat as context.

## Purpose

<!-- Describe what this skill does in one sentence. -->

## When to use

- <!-- situation 1 -->
- <!-- situation 2 -->

## Instructions

<!-- Step-by-step instructions Claude should follow when this skill is invoked. -->

1. 
2. 
3. 

## Constraints

- Do not modify files outside the scope of the current spec.
- Report findings before making changes unless the task is clearly mechanical.

## Customize

Edit this file to add project-specific commands or constraints:

```
# Example:
# command: pytest tests/ -x -q
# scope: src/
```
"""


def _find_project_root(start: Path) -> Path:
    current = start
    for _ in range(10):
        if (current / ".specify").exists():
            return current
        current = current.parent
    return start


def _skills_dir(project_root: Path) -> Path:
    return project_root / ".claude" / "skills"


def _collect_skills(project_root: Path) -> dict[str, Path]:
    skills: dict[str, Path] = {}
    base = _skills_dir(project_root)
    if base.exists():
        for p in sorted(base.glob("*.md")):
            skills[p.stem] = p
    custom = base / "custom"
    if custom.exists():
        for p in sorted(custom.glob("*.md")):
            skills[f"custom/{p.stem}"] = p
    return skills


def _open_editor(path: Path) -> None:
    editor = os.environ.get("EDITOR") or os.environ.get("VISUAL")
    if editor:
        subprocess.run([editor, str(path)])
    elif sys.platform == "darwin":
        subprocess.run(["open", "-t", str(path)])
    elif sys.platform == "win32":
        subprocess.run(["notepad", str(path)])
    else:
        console.print(f"[yellow]Set $EDITOR to open files automatically.[/]")
        console.print(f"File: [cyan]{path}[/]")


@skill_app.command("list")
def skill_list() -> None:
    """List all skills (built-in and custom)."""
    project_root = _find_project_root(Path.cwd())
    skills = _collect_skills(project_root)

    if not skills:
        console.print("[yellow]No skills found.[/] Run [bold]sdd init --agent claude-code --profile standard[/] to scaffold built-in skills.")
        raise typer.Exit()

    table = Table(title="Skills", show_lines=True)
    table.add_column("Name", style="cyan")
    table.add_column("Type")
    table.add_column("Path")

    for key, path in skills.items():
        kind = "[green]custom[/]" if key.startswith("custom/") else "[dim]built-in[/]"
        table.add_row(key, kind, str(path.relative_to(project_root)))

    console.print(table)
    console.print("\n[dim]Invoke with: /skill <name> (Claude Code)[/]\n")


@skill_app.command("new")
def skill_new(
    name: str = typer.Argument(..., help="Skill name (slug, e.g. 'format-code' or 'check-types')"),
    description: str = typer.Option("", "--description", "-d", help="Short description of what this skill does"),
) -> None:
    """Scaffold a new custom skill in .claude/skills/custom/."""
    project_root = _find_project_root(Path.cwd())
    custom_dir = _skills_dir(project_root) / "custom"
    custom_dir.mkdir(parents=True, exist_ok=True)

    dest = custom_dir / f"{name}.md"
    if dest.exists():
        console.print(f"[red]Skill already exists:[/] {dest}")
        raise typer.Exit(1)

    content = CUSTOM_SKILL_TEMPLATE.format(name=name)
    if description:
        content = content.replace("<!-- Describe what this skill does in one sentence. -->", description)

    dest.write_text(content, encoding="utf-8", newline="\n")
    console.print(f"\n[bold green]Created[/] custom skill at [cyan]{dest}[/]")
    console.print(f"Invoke with: [bold]/skill {name}[/] (Claude Code)\n")

    _open_editor(dest)


@skill_app.command("edit")
def skill_edit(
    name: str = typer.Argument(..., help="Skill name (e.g. 'lint' or 'custom/format-code')"),
) -> None:
    """Open a skill file in your editor."""
    project_root = _find_project_root(Path.cwd())
    skills = _collect_skills(project_root)

    if name not in skills:
        console.print(f"[red]Skill '{name}' not found.[/] Run [bold]sdd skill list[/] to see available skills.")
        raise typer.Exit(1)

    _open_editor(skills[name])


@skill_app.command("show")
def skill_show(
    name: str = typer.Argument(..., help="Skill name"),
) -> None:
    """Print the content of a skill file."""
    project_root = _find_project_root(Path.cwd())
    skills = _collect_skills(project_root)

    if name not in skills:
        console.print(f"[red]Skill '{name}' not found.[/]")
        raise typer.Exit(1)

    content = skills[name].read_text(encoding="utf-8")
    console.rule(f"[bold cyan]{name}[/]")
    console.print(content)
    console.rule()
